package com.sofia.miformacionctma.ui.screens
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.sofia.miformacionctma.domain.Prioridad
import com.sofia.miformacionctma.ui.state.FormularioActividadUiState
@OptIn(ExperimentalMaterial3Api::class)
@Composable fun FormularioActividad(uiState:FormularioActividadUiState,onTituloChange:(String)->Unit,onDescripcionChange:(String)->Unit,onFechaChange:(String)->Unit,onPrioridadChange:(Prioridad)->Unit,onProgresoChange:(String)->Unit,onGuardar:()->Unit,modifier:Modifier=Modifier){var menu by remember{mutableStateOf(false)};Column(modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){OutlinedTextField(uiState.titulo,onTituloChange,label={Text("Título")},isError=uiState.errorTitulo!=null,supportingText={uiState.errorTitulo?.let{Text(it)}},modifier=Modifier.fillMaxWidth());OutlinedTextField(uiState.descripcion,onDescripcionChange,label={Text("Descripción (opcional)")},isError=uiState.errorDescripcion!=null,supportingText={uiState.errorDescripcion?.let{Text(it)}},modifier=Modifier.fillMaxWidth());OutlinedTextField(uiState.fecha,onFechaChange,label={Text("Fecha (AAAA-MM-DD)")},isError=uiState.errorFecha!=null,supportingText={uiState.errorFecha?.let{Text(it)}},modifier=Modifier.fillMaxWidth());ExposedDropdownMenuBox(expanded=menu,onExpandedChange={menu=!menu}){OutlinedTextField(uiState.prioridad.name,{},readOnly=true,label={Text("Prioridad")},trailingIcon={ExposedDropdownMenuDefaults.TrailingIcon(menu)},modifier=Modifier.menuAnchor().fillMaxWidth());ExposedDropdownMenu(expanded=menu,onDismissRequest={menu=false}){Prioridad.entries.forEach{p->DropdownMenuItem(text={Text(p.name)},onClick={onPrioridadChange(p);menu=false})}}};OutlinedTextField(uiState.progreso,onProgresoChange,label={Text("Progreso (0-100)")},isError=uiState.errorProgreso!=null,supportingText={uiState.errorProgreso?.let{Text(it)}},modifier=Modifier.fillMaxWidth());Button(onClick=onGuardar,enabled=uiState.puedeGuardar,modifier=Modifier.fillMaxWidth()){Text("Guardar actividad")}}}
